[features]
seeds = false
skip-lint = false
[programs.localnet]
new = "EJ6XSF9BUjwz5N8fpVrz32LjiZTvMhx2xAE7V5ua6fCd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kenxsantos/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
