[features]
seeds = false
skip-lint = false
[programs.localnet]
contract = "kUYDNphoAWLa3ZWbY6rfMrYXRzhKv2GH7UyYwYcxq2Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kenxsantos/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
